[book]
title = "The 48 Laws of Power"
authors = ["Rishabh"]
description = ""
language = "en"
multilingual = false
src = "src"

[build]
create-missing = false

[rust]
edition = "2018"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/constorion/the_48_laws_of_power"
git-repository-icon = "fa-github"
mathjax-support = true